/**
 * Clash / Mihomo 渲染器
 *
 * - 输入：Parser.js 产出的标准化 Node[]
 *
 * - 当前支持的节点类型：
 *   • Shadowsocks ：type = "ss"
 *   • Trojan      ：type = "trojan"
 *   • Hysteria2   ：type = "hysteria2" 或 "hy2"
 *
 * - 典型使用方式：
 *   /autosub?id=你的id&client=clash
 *
 * - 适配客户端（只负责生成 YAML，是否支持协议看客户端本身）：
 *   Clash Meta / Mihomo / Clash Verge / Clash for Windows /
 *   FIClash / Nekobox / FlyClash 等
 */

/** 安全取字符串 */
function pickString(v, fallback = "") {
  if (v === null || v === undefined) return fallback;
  const s = String(v).trim();
  return s || fallback;
}

/** 安全取数字 */
function pickNumber(v, fallback) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

/** YAML 内联 map 字符串化：- { key: "val", port: 443, udp: true } */
function formatInlineMap(obj, indent = "  ") {
  const parts = [];
  for (const [key, value] of Object.entries(obj)) {
    if (value === undefined || value === null || value === "") continue;

    let rendered;
    if (typeof value === "number" || typeof value === "boolean") {
      rendered = String(value);
    } else {
      const s = String(value)
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"');
      rendered = `"${s}"`;
    }
    parts.push(`${key}: ${rendered}`);
  }

  if (!parts.length) return null;
  return `${indent}- { ${parts.join(", ")} }`;
}

/**
 * Node -> Clash proxy 对象（纯 JS 对象，后面再拼成 YAML）
 */
function nodeToClashProxy(node) {
  if (!node || !node.type) return null;

  const server = pickString(node.server);
  const port = pickNumber(node.port);
  const nameBase =
    pickString(node.name) || (server && port ? `${server}:${port}` : "");
  const name = nameBase || "Unnamed";

  // ---------- SS ----------
  if (node.type === "ss") {
    const cipher = pickString(node.cipher);
    const password = pickString(node.password);

    if (!server || !port || !cipher || !password) return null;

    const proxy = {
      name,
      type: "ss",
      server,
      port,
      cipher,
      password,
    };

    if (node.plugin) proxy.plugin = node.plugin;
    if (node.pluginOpts) proxy["plugin-opts"] = node.pluginOpts;

    return proxy;
  }

  // ---------- Trojan ----------
  if (node.type === "trojan") {
    const password = pickString(node.password);
    if (!server || !port || !password) return null;

    const proxy = {
      name,
      type: "trojan",
      server,
      port,
      password,
    };

    // 典型 Clash trojan 字段
    const sni = pickString(node.sni || node.host);
    if (sni) proxy.sni = sni;

    if (typeof node.skipCertVerify === "boolean") {
      proxy["skip-cert-verify"] = node.skipCertVerify;
    }

    // 是否 WS
    const net = pickString(node.network || node.net || "").toLowerCase();
    if (net === "ws" || net === "websocket") {
      proxy.network = "ws";

      const path = pickString(node.path || node.wsPath || "/");
      const hostHeader = pickString(
        node.host ||
          (node.wsHeaders && node.wsHeaders.Host) ||
          (node.wsHeaders && node.wsHeaders.host)
      );

      const wsOpts = {};
      if (path) wsOpts.path = path;
      if (hostHeader) {
        wsOpts.headers = { Host: hostHeader };
      }

      if (Object.keys(wsOpts).length) {
        proxy["ws-opts"] = wsOpts;
      }
    }

    return proxy;
  }

  // ---------- Hysteria2 / hy2 ----------
  if (node.type === "hysteria2" || node.type === "hy2") {
    const password = pickString(node.password || node.auth);
    if (!server || !port || !password) return null;

    const proxy = {
      name,
      type: "hysteria2",
      server,
      port,
      // 兼容：有的机场/客户端使用 auth，有的使用 password
      auth: password,
      password: password,
    };

    const sni = pickString(node.sni || node.peer || node.serverName);
    if (sni) proxy.sni = sni;

    if (typeof node.skipCertVerify === "boolean") {
      proxy["skip-cert-verify"] = node.skipCertVerify;
    }

    // 端口跳跃区间（如 35000-39000）
    const ports = pickString(node.ports || node.portRange);
    if (ports) proxy.ports = ports;

    // UDP / fast-open
    if (typeof node.udp === "boolean") proxy.udp = node.udp;
    if (typeof node.fastOpen === "boolean") {
      proxy["fast-open"] = node.fastOpen;
    }

    // obfs / protocol 之类字段（有就带，客户端不认识会自动忽略）
    const obfs = pickString(node.obfs);
    if (obfs) proxy.obfs = obfs;

    return proxy;
  }

  // 其它协议暂时不渲染到 Clash
  return null;
}

/**
 * 渲染入口
 *
 * @param {Array} nodes - Parser.js 解析后的 Node[]
 * @returns {{body: string, contentType: string}}
 */
export function renderClash(nodes = []) {
  const proxies = [];

  for (const n of nodes) {
    const p = nodeToClashProxy(n);
    if (p) proxies.push(p);
  }

  const names = proxies.map((p) => p.name);

  const lines = [];

  // ===== 头部：参考“赔钱机场.yaml”风格，保持兼容性 =====
  lines.push(`# Generated by Lyn autosub`);
  lines.push(`mixed-port: 7890`);
  lines.push(`allow-lan: true`);
  lines.push(`mode: rule`);
  lines.push(`log-level: info`);
  lines.push(`external-controller: '127.0.0.1:9090'`);
  lines.push(``);
  lines.push(`dns:`);
  lines.push(`  enable: true`);
  lines.push(`  ipv6: false`);
  lines.push(`  nameserver: [223.5.5.5, 223.6.6.6]`);
  lines.push(``);

  // ===== proxies =====
  lines.push(`proxies:`);

  if (proxies.length === 0) {
    lines.push(`  # 没有解析出任何可用节点`);
  } else {
    for (const p of proxies) {
      const line = formatInlineMap(p, "  ");
      if (line) lines.push(line);
    }
  }

  // ===== proxy-groups =====
  lines.push(``);
  lines.push(`proxy-groups:`);
  lines.push(`  - name: "🐹Lyn · Node"`);
  lines.push(`    type: select`);
  lines.push(`    proxies:`);

  if (names.length === 0) {
    lines.push(`      - DIRECT`);
  } else {
    lines.push(`      - DIRECT`);
    for (const name of names) {
      lines.push(`      - "${name}"`);
    }
  }

  // ===== rules =====
  lines.push(``);
  lines.push(`rules:`);
  lines.push(`  - GEOIP,LAN,DIRECT`);
  lines.push(`  - GEOIP,CN,DIRECT`);
  lines.push(`  - MATCH,🐹Lyn · Node`);

  return {
    body: lines.join("\n"),
    contentType: "text/yaml; charset=utf-8",
  };
}
