/* renderers/surge.js
 * 职责：
 *   - Node[] → Surge 节点行
 *   - 只输出 [Proxy] 部分，不包含 [Proxy Group] / [Rule]
 */

function escapeName(name) {
    return String(name || "").replace(/,/g, "，");
}

/* Node → Surge 单条 Proxy 行 */
function nodeToSurgeLine(node) {
    if (!node || !node.type) return null;

    const type = String(node.type).toLowerCase();

    const server =
        node.server ||
        node.add ||
        node.address ||
        node.host ||
        "";
    const port = Number(node.port || node.server_port || 0);
    if (!server || !port) return null;

    const name = node.name || `${server}:${port}`;

    // Shadowsocks
    if (type === "ss") {
        const cipher = node.cipher || node.method;
        const password = node.password;
        if (!cipher || !password) return null;

        return `${escapeName(name)} = ss, ${server}, ${port}, encrypt-method=${cipher}, password=${password}, udp-relay=true`;
    }

    // Trojan
    if (type === "trojan") {
        const password = node.password;
        if (!password) return null;

        const sni =
            node.sni ||
            node.host ||
            "";
        const parts = [
            `${escapeName(name)} = trojan, ${server}, ${port}, password=${password}`,
        ];
        if (sni) parts.push(`sni=${sni}`);
        parts.push("udp-relay=true");
        return parts.join(", ");
    }

    // VMess
    if (type === "vmess") {
        const uuid = node.uuid || node.id;
        if (!uuid) return null;

        const net =
            node.network ||
            node.net ||
            node.type ||
            "tcp";
        const sni =
            node.sni ||
            node.host ||
            "";
        const tls = node.tls !== false;

        const parts = [
            `${escapeName(name)} = vmess, ${server}, ${port}, username=${uuid}`,
        ];
        if (tls) parts.push("tls=true");
        if (sni) parts.push(`sni=${sni}`);

        if (net === "ws") {
            const path = node.path || "/";
            const host =
                node.host ||
                sni ||
                "";
            parts.push("ws=true");
            parts.push(`ws-path=${path}`);
            if (host) parts.push(`ws-headers=Host:${host}`);
        }

        return parts.join(", ");
    }

    // VLESS
    if (type === "vless") {
        const uuid = node.uuid;
        if (!uuid) return null;

        const net =
            node.network ||
            node.net ||
            node.type ||
            "tcp";
        const sni =
            node.sni ||
            node.host ||
            "";
        const tls = node.tls !== false;

        const parts = [
            `${escapeName(name)} = vless, ${server}, ${port}, username=${uuid}`,
        ];
        if (tls) parts.push("tls=true");
        if (sni) parts.push(`sni=${sni}`);

        if (net === "ws") {
            const path = node.path || "/";
            const host =
                node.host ||
                sni ||
                "";
            parts.push("ws=true");
            parts.push(`ws-path=${path}`);
            if (host) parts.push(`ws-headers=Host:${host}`);
        }

        return parts.join(", ");
    }

    // Hysteria2 / hy2 / hysteria
    if (type === "hysteria2" || type === "hy2" || type === "hysteria") {
        const password = node.password || node.auth;
        if (!password) return null;

        const parts = [
            `${escapeName(name)} = hysteria2, ${server}, ${port}, password=${password}`,
        ];

        if (node.sni || node.peer) {
            parts.push(`sni=${node.sni || node.peer}`);
        }
        if (node.upmbps || node.up) {
            parts.push(`up=${node.upmbps || node.up}`);
        }
        if (node.downmbps || node.down) {
            parts.push(`down=${node.downmbps || node.down}`);
        }
        if (node.alpn) {
            parts.push(`alpn=${node.alpn}`);
        }
        if (node.skipCertVerify) {
            parts.push("skip-cert-verify=true");
        }

        return parts.join(", ");
    }

    return null;
}

/* Node[] → Surge 文本，只含 [Proxy] 段 */
export function renderSurge(nodes = [], meta = {}) {
    const proxyLines = [];

    for (const n of nodes || []) {
        const line = nodeToSurgeLine(n);
        if (!line) continue;
        proxyLines.push(line);
    }

    const lines = [];
    lines.push("# Generated by autosub (Surge Proxies Only)");
    lines.push("");
    lines.push("[Proxy]");
    if (proxyLines.length === 0) {
        lines.push("# (no valid proxies parsed)");
    } else {
        lines.push(...proxyLines);
    }

    return {
        body: lines.join("\n"),
        contentType: "text/plain; charset=utf-8",
    };
}