name = "paste"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = false

# 只处理 aura.us.kg 下的 /api/paste 路径
[[routes]]
pattern = "aura.us.kg/api/paste*"
custom_domain = true

# 绑定 KV：Paste_KV
[[kv_namespaces]]
binding = "PASTE"                  # 代码里用 env.PASTE
id = "0cbff5cb99e74e18942a6d3c5efbe94c"